name: deepin-voice-recorder
version: '0.1' 
summary: deepin-voice-recorder
description: |
  This is deepin-voice-recorder snap application

grade: stable
confinement: strict

apps:
  deepin-voice-recorder:
    command: bin/wrapper
    plugs:
      - network
      - unity7
      - x11
      - home
      - opengl
      - pulseaudio
      - browser-support

plugs:
  alsa: null
  home: null

parts:
  app:
    source: .
    plugin: qmake
    qt-version: qt5
    options:
      - DEFINES += SNAP_APP
    stage-packages:
      - overlay-scrollbar-gtk2
      - libgail-3-0
      - libatk-bridge2.0-0
      - libatk-adaptor
      - unity-gtk2-module:amd64
      - libcanberra-gtk-module:amd64
      - fonts-wqy-zenhei
      - libqt5multimedia5
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-ugly
      - libqt5multimedia5-plugins
      - gstreamer1.0-plugins-good
      - libasound2
      - libsoundtouch1
      - gstreamer1.0-plugins-bad-videoparsers
      - gstreamer1.0-plugins-bad-faad
      - libasound2-data
      - alsa-utils
    after: [desktop-qt5]

  wrapper:
    plugin: dump
    source: files/
